spring.application.name=muqu

# PostgreSQL 配置
# jdbc.url=jdbc:postgresql://localhost:7758/postgres
# jdbc.username=postgres
# jdbc.password=ysdww9520
# jdbc.driver=org.postgresql.Driver

jdbc.url=jdbc:postgresql://localhost:5432/postgres
jdbc.username=postgres
jdbc.password=ysdww9520
jdbc.driver=org.postgresql.Driver




# 连接池配置（HikariCP）
jdbc.pool.maxsize=20
jdbc.pool.minsize=5
jdbc.pool.timeout=30000
jdbc.pool.maxlifetime=1800000

# pg_ctl -D "C:\Shengde\database" -l logfile start
# .\psql -U postgres
